- name: Add IP address of all hosts to all hosts
  become: true
  lineinfile:
    dest: /etc/hosts
    line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].inventory_hostname }}"
    state: present
  with_items: "{{ groups.all }}"

- name: Copy the slaves file
  become: true
  template:
    src: ./templates/slaves.j2
    dest: "{{ SPARK_HOME }}/conf/slaves"

- name: Copy the spark-env file
  become: true
  template:
    src: ./templates/spark-env.sh.j2
    dest: "{{ SPARK_HOME }}/conf/spark-env.sh"