---
- name: Update apt packages
  become: true
  apt:
    update_cache: yes
- name: Install required packages
  become: true
  package: name={{ item }} state=present
  with_items:
   - python-software-properties 
   - openssh-server 
   - openssh-client 